org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
# 工程路径含中文（D:\ai模型训练\...），显式关闭 AGP 的路径检查
android.overridePathCheck=true

kotlin.code.style=official
